
[1;37mFeature: Ensure that all admin pages work                [1;30m# tests/features/admin.feature:1[0m

[1;37m  Scenario: Make sure the site's main page loads         [1;30m# tests/features/admin.feature:2[0m
[1;30m    Given I sign is as an admin user                     [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                     [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin"            [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin"            [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Future Home of the Admin Console" [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "Future Home of the Admin Console" [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: Make sure the admin user index loads         [1;30m# tests/features/admin.feature:7[0m
[1;30m    Given I sign is as an admin user                     [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                     [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin/users"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin/users"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Add User"                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "Add User"                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: Make sure the admin new user page loads      [1;30m# tests/features/admin.feature:12[0m
[1;30m    Given I sign is as an admin user                     [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                     [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin/users/new"  [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin/users/new"  [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "New User"                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "New User"                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I fill in "email" with "user2@example.com"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[A[1;32m    When I fill in "email" with "user2@example.com"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[1;30m    And I fill in "name" with "Admin name"               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[A[1;32m    And I fill in "name" with "Admin name"               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[1;30m    And I fill in "organization" with "Ibesr Haiti"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[A[1;32m    And I fill in "organization" with "Ibesr Haiti"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[1;30m    And I fill in "phone" with "1234567890"              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[A[1;32m    And I fill in "phone" with "1234567890"              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[1;30m    And I select "admin" from "role"                     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:340[0m
[A[1;32m    And I select "admin" from "role"                     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:340[0m
[1;30m    When I press "Submit"                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[A[1;32m    When I press "Submit"                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[1;30m    And I wait "2" seconds                               [1;30m# tests/features/steps.py:15[0m
[A[1;32m    And I wait "2" seconds                               [1;30m# tests/features/steps.py:15[0m
[1;30m    And I go to "http://localhost:8080/admin/users"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin/users"      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "user2@example.com"                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "user2@example.com"                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37mFeature: Ensure that the admin dashboard pages work         [1;30m# tests/features/admin_dashboard.feature:1[0m

[1;37m  Scenario: Make sure the admin new organization page loads [1;30m# tests/features/admin_dashboard.feature:2[0m
[1;30m    Given I sign is as an admin user                        [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                        [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin/dashboard"     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin/dashboard"     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Initiated By"                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "Initiated By"                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: Make sure the admin new organization page loads [1;30m# tests/features/admin_dashboard.feature:2[0m
[1;30m    Given I sign is as an admin user                        [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                        [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin/dashboard"     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin/dashboard"     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    When I click on "View"                                  [1;30m# tests/features/steps.py:5[0m
[A[1;32m    When I click on "View"                                  [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Dashboard Item"                      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "Dashboard Item"                      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37mFeature: Testing the Navigation Bar                            [1;30m# tests/features/admin_navigation.feature:1[0m

[1;37m  Scenario: Make sure the navigation bar has the correct links [1;30m# tests/features/admin_navigation.feature:2[0m
[1;30m    Given I sign is as an admin user                           [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                           [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin"                  [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin"                  [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    When I click on "Users"                                    [1;30m# tests/features/steps.py:5[0m
[A[1;32m    When I click on "Users"                                    [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Add User"                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "Add User"                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Organizations"                            [1;30m# tests/features/steps.py:5[0m
[A[1;32m    When I click on "Organizations"                            [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Add Organizations"                      [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;31m    Then I should see "Add Organizations"                      [1;41;33m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py", line 158, in should_see
        assert_true(step, contains_content(world.browser, text))
      File "/usr/local/lib/python2.7/dist-packages/lettuce_webdriver/util.py", line 35, in assert_true
        nose_assert_true(exp)
      File "/usr/local/lib/python2.7/dist-packages/lettuce_webdriver/util.py", line 35, in assert_true
        nose_assert_true(exp)
      File "/usr/lib/python2.7/unittest/case.py", line 424, in assertTrue
        raise self.failureException(msg)
    AssertionError: Then I should see "Add Organizations"[0m
[1;30m    When I click on "Services"                                 [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Services"                                 [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Add Services"                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Add Services"                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Programs"                                 [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Programs"                                 [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Add Programs"                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Add Programs"                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Records"                                  [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Records"                                  [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "See Record History"                     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "See Record History"                     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Manual"                                   [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Manual"                                   [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Timoun Manual"                          [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Timoun Manual"                          [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Profile"                                  [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Profile"                                  [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Name"                                   [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Name"                                   [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Dashboard"                                [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Dashboard"                                [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Initiated By"                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Initiated By"                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Logout"                                   [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Logout"                                   [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Future Home"                            [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Future Home"                            [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37mFeature: Ensure that all admin organization pages work                                                  [1;30m# tests/features/admin_organizations.feature:1[0m

[1;37m  Scenario: Make sure the admin new organization page loads                                             [1;30m# tests/features/admin_organizations.feature:2[0m
[1;30m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin/organizations/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "New Organization"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[1;32m    Then I should see "New Organization"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to create a new user, and see it reflected on the Audit page               [1;30m# tests/features/admin_organizations.feature:7[0m
[1;30m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[A[1;32m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[1;32m    And I go to "http://localhost:8080/admin/organizations/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    And I fill in "name" with "Org name"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[A[1;32m    And I fill in "name" with "Org name"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[1;30m    When I press "Submit"                                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[A[0;31m    When I press "Submit"                                                                               [1;41;33m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py", line 228, in press_button
        button.click()
      File "/usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py", line 228, in press_button
        button.click()
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 60, in click
        self._execute(Command.CLICK_ELEMENT)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webelement.py", line 370, in _execute
        return self._parent.execute(command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 378, in _request
        resp = self._conn.getresponse()
      File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 409, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 365, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    AssertionError: When I press "Submit", failed because: [0m
[1;30m    And I wait "2" seconds                                                                              [1;30m# tests/features/steps.py:15[0m
[A[0;36m    And I wait "2" seconds                                                                              [1;30m# tests/features/steps.py:15[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I go to "http://localhost:8080/admin/dashboard"                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    When I go to "http://localhost:8080/admin/dashboard"                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    And I should see "Create Organization"                                                              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    And I should see "Create Organization"                                                              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to view an existing user                                                   [1;30m# tests/features/admin_organizations.feature:20[0m
[1;30m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                                    [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
      File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    CannotSendRequest[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Org name"                                                                          [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Org name"                                                                          [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Org name Profile"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org name Profile"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    And I should see "Name"                                                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    And I should see "Name"                                                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to edit an existing user, and see it reflected on the Audit page           [1;30m# tests/features/admin_organizations.feature:28[0m
[1;30m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                                    [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 791, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 772, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 111] Connection refused[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Org name"                                                                          [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Org name"                                                                          [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Org name Profile"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org name Profile"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I change "name" to "Org edit" on the form                                                      [1;30m# tests/features/steps.py:28[0m
[A[0;36m    When I change "name" to "Org edit" on the form                                                      [1;30m# tests/features/steps.py:28[0m
[1;30m    And I press "Submit"                                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[A[0;36m    And I press "Submit"                                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[1;30m    Then I should see "Organization updated successfully"                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Organization updated successfully"                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    And I should see "Org edit"                                                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    And I should see "Org edit"                                                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I go to "http://localhost:8080/admin/dashboard"                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    When I go to "http://localhost:8080/admin/dashboard"                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Edit Organization"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Edit Organization"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to see the Audit page for Organizations                                    [1;30m# tests/features/admin_organizations.feature:42[0m
[1;30m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                                    [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
      File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    CannotSendRequest[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    When I click on "See Organization Changes"                                                          [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "See Organization Changes"                                                          [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Organization Affected"                                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Organization Affected"                                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to delete an existing organization, and see it reflected on the Audit page [1;30m# tests/features/admin_organizations.feature:48[0m
[1;30m    Given I sign is as an admin user                                                                    [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                                    [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 791, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 772, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 111] Connection refused[0m
[1;30m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/organizations"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Org edit"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org edit"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Org edit"                                                                          [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Org edit"                                                                          [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Org edit Profile"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Org edit Profile"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click "Delete Organization" and confirm the popup                                            [1;30m# tests/features/steps.py:33[0m
[A[0;36m    When I click "Delete Organization" and confirm the popup                                            [1;30m# tests/features/steps.py:33[0m
[1;30m    And I wait "2" seconds                                                                              [1;30m# tests/features/steps.py:15[0m
[A[0;36m    And I wait "2" seconds                                                                              [1;30m# tests/features/steps.py:15[0m
[1;30m    Then I should see "deleted"                                                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "deleted"                                                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I go to "http://localhost:8080/admin/dashboard"                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    When I go to "http://localhost:8080/admin/dashboard"                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Delete Organization"                                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Delete Organization"                                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37mFeature: Ensure that all admin program pages work                                                  [1;30m# tests/features/admin_programs.feature:1[0m

[1;37m  Scenario: Make sure the admin new progrm page loads                                              [1;30m# tests/features/admin_programs.feature:2[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
      File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    CannotSendRequest[0m
[1;30m    And I go to "http://localhost:8080/admin/programs/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "New Program"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "New Program"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to create a new program, and see it reflected on the Audit page       [1;30m# tests/features/admin_programs.feature:7[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 791, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 772, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 111] Connection refused[0m
[1;30m    And I go to "http://localhost:8080/admin/programs/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    And I fill in "name" with "Program name"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[A[0;36m    And I fill in "name" with "Program name"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[1;30m    When I press "Submit"                                                                          [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[A[0;36m    When I press "Submit"                                                                          [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[1;30m    And I wait "2" seconds                                                                         [1;30m# tests/features/steps.py:15[0m
[A[0;36m    And I wait "2" seconds                                                                         [1;30m# tests/features/steps.py:15[0m
[1;30m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    And I should see "Create Program"                                                              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    And I should see "Create Program"                                                              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to view an existing program                                           [1;30m# tests/features/admin_programs.feature:20[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
      File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    CannotSendRequest[0m
[1;30m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Program name"                                                                 [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Program name"                                                                 [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Program name Profile"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program name Profile"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    And I should see "Name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    And I should see "Name"                                                                        [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to edit an existing user, and see it reflected on the Audit page      [1;30m# tests/features/admin_programs.feature:28[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 791, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 772, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 111] Connection refused[0m
[1;30m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Program name"                                                                 [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Program name"                                                                 [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Program name Profile"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program name Profile"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I change "name" to "Program edit" on the form                                             [1;30m# tests/features/steps.py:28[0m
[A[0;36m    When I change "name" to "Program edit" on the form                                             [1;30m# tests/features/steps.py:28[0m
[1;30m    And I press "Submit"                                                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[A[0;36m    And I press "Submit"                                                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[1;30m    Then I should see "Program updated successfully"                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program updated successfully"                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    And I should see "Program edit"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    And I should see "Program edit"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Edit Program"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Edit Program"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to see the Audit page for Programs                                    [1;30m# tests/features/admin_programs.feature:42[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
      File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    CannotSendRequest[0m
[1;30m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    When I click on "See Program Changes"                                                          [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "See Program Changes"                                                          [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Program Affected"                                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program Affected"                                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to delete an existing program, and see it reflected on the Audit page [1;30m# tests/features/admin_programs.feature:48[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 791, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 772, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 111] Connection refused[0m
[1;30m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/programs"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Program edit"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program edit"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "Program edit"                                                                 [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "Program edit"                                                                 [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "Program edit Profile"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Program edit Profile"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click "Delete Program" and confirm the popup                                            [1;30m# tests/features/steps.py:33[0m
[A[0;36m    When I click "Delete Program" and confirm the popup                                            [1;30m# tests/features/steps.py:33[0m
[1;30m    And I wait "2" seconds                                                                         [1;30m# tests/features/steps.py:15[0m
[A[0;36m    And I wait "2" seconds                                                                         [1;30m# tests/features/steps.py:15[0m
[1;30m    Then I should see "deleted"                                                                    [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "deleted"                                                                    [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Delete Program"                                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Delete Program"                                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37mFeature: Ensure that all admin record pages work      [1;30m# tests/features/admin_records.feature:1[0m

[1;37m  Scenario: Make sure the admin new record page loads [1;30m# tests/features/admin_records.feature:2[0m
[1;30m    Given I sign is as an admin user                  [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                  [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
      File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    CannotSendRequest[0m
[1;30m    And I go to "http://localhost:8080/admin/records" [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/records" [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "See Record History"            [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "See Record History"            [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: Make sure the admin new progrm page loads [1;30m# tests/features/admin_records.feature:7[0m
[1;30m    Given I sign is as an admin user                  [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                  [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 791, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 772, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 111] Connection refused[0m
[1;30m    And I go to "http://localhost:8080/admin/records" [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/records" [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "First org"                     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "First org"                     [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I click on "First org"                       [1;30m# tests/features/steps.py:5[0m
[A[0;36m    When I click on "First org"                       [1;30m# tests/features/steps.py:5[0m
[1;30m    Then I should see "source_de_financement"         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "source_de_financement"         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37mFeature: Ensure that all admin service pages work                                                  [1;30m# tests/features/admin_services.feature:1[0m

[1;37m  Scenario: Make sure the admin new service page loads                                             [1;30m# tests/features/admin_services.feature:2[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1001, in _send_request
        self.putrequest(method, url, **skips)
      File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
        raise CannotSendRequest()
    CannotSendRequest[0m
[1;30m    And I go to "http://localhost:8080/admin/services/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/services/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "New Service"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "New Service"                                                                [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m

[1;37m  Scenario: I should be able to create a new service, and see it reflected on the Audit page       [1;30m# tests/features/admin_services.feature:7[0m
[1;30m    Given I sign is as an admin user                                                               [1;30m# tests/features/steps.py:19[0m
[A[0;31m    Given I sign is as an admin user                                                               [1;41;33m# tests/features/steps.py:19[0m
[1;31m    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/lettuce/core.py", line 144, in __call__
        ret = self.function(self.step, *args, **kw)
      File "/home/andy/appengine-1.9/google_appengine/timoun/tests/features/steps.py", line 20, in given_i_sign_is_as_an_admin_user
        world.browser.get("http://localhost:8080/users/login")
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 185, in get
        self.execute(Command.GET, {'url': url})
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 171, in execute
        response = self.command_executor.execute(driver_command, params)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 347, in execute
        return self._request(command_info[0], url, body=data)
      File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 377, in _request
        self._conn.request(method, parsed_url.path, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 973, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1007, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 969, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 829, in _send_output
        self.send(msg)
      File "/usr/lib/python2.7/httplib.py", line 791, in send
        self.connect()
      File "/usr/lib/python2.7/httplib.py", line 772, in connect
        self.timeout, self.source_address)
      File "/usr/lib/python2.7/socket.py", line 571, in create_connection
        raise err
    error: [Errno 111] Connection refused[0m
[1;30m    And I go to "http://localhost:8080/admin/services/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/services/new"                                         [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    And I fill in "name" with "Service name"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[A[0;36m    And I fill in "name" with "Service name"                                                       [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:200[0m
[1;30m    When I press "Submit"                                                                          [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[A[0;36m    When I press "Submit"                                                                          [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:225[0m
[1;30m    And I wait "2" seconds                                                                         [1;30m# tests/features/steps.py:15[0m
[A[0;36m    And I wait "2" seconds                                                                         [1;30m# tests/features/steps.py:15[0m
[1;30m    And I go to "http://localhost:8080/admin/services"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    And I go to "http://localhost:8080/admin/services"                                             [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Service name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Service name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[A[0;36m    When I go to "http://localhost:8080/admin/dashboard"                                           [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:76[0m
[1;30m    Then I should see "Service name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    Then I should see "Service name"                                                               [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[1;30m    And I should see "Create Service"                                                              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
[A[0;36m    And I should see "Create Service"                                                              [1;30m# usr/local/lib/python2.7/dist-packages/lettuce_webdriver/webdriver.py:157[0m
Died with 

[1;37m6 features ([1;32m2 passed[1;37m)[0m
[1;37m20 scenarios ([1;32m6 passed[1;37m)[0m
[1;37m143 steps ([0;31m14 failed[1;37m, [0;36m93 skipped[1;37m, [1;32m36 passed[1;37m)[0m
========================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

